project:
  type: website
website:
  title: "STA 701S 2023-2024"
  navbar:
    background: "#353148"
    align: center
    collapse-below: lg
  
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  repo-url: https://github.com/merliseclyde/sta701-F23
  repo-actions: [issue]
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Merlise Clyde"
    background: "#353148"
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

callout-appearance: simple
